### ISSUE TITLE
new logo ideas

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#10]
Let's make some draft logo ideas for the rename to Open Seattle!

**Comment by sethvincent** [comment]
So far my only idea is stealing the [nwdata.org](http://nwdata.org) logo. Which is totally ok, since I made it.

![open-seattle](https://cloud.githubusercontent.com/assets/164214/8066908/2f6119e4-0e9f-11e5-9ebf-1502a0b4e1ac.jpg)

I didn't add colors yet, because I'm kinda bad at colors.

**Comment by loganfranken** [comment]
I like it!

**Comment by willscott** [comment]
:+1:

**Comment by JohnTigue** [comment]
I like. Angle brackets might be worth comparing, but then everything is sharp edges (["Harmony of form consists in the proper balancing, and contrast of, the straight, the inclined, and the curved"](http://www.bc.edu/bc_org/avp/cas/fnart/fa267/grammar/propositions.html)).

Any thoughts about [color](https://www.google.com/search?q=cascadia+flag&tbm=isch)?

**Comment by karenwittekind** [comment]
New to the group - just thought I'd offer some logo ideas

![openseattle1](https://cloud.githubusercontent.com/assets/11412379/8451557/03046468-1f99-11e5-9ab8-a32e33b98052.png)
![openseattle2](https://cloud.githubusercontent.com/assets/11412379/8451558/03195cd8-1f99-11e5-852c-79ad4aaebc4a.png)
![openseattle3](https://cloud.githubusercontent.com/assets/11412379/8451560/0320070e-1f99-11e5-8b44-ff5fbc3fe88d.png)
![openseattle4](https://cloud.githubusercontent.com/assets/11412379/8451559/031ed0f0-1f99-11e5-93bd-55a9531c4aaf.png)

**Comment by ptressel** [comment]
Hmm, if this is "open", don't the brackets have to face the other way?

} ^ {

;-)

**Comment by sethvincent** [comment]
@karenwittekind those are great! Do you plan on making it to the [Thursday meetup this week](http://www.meetup.com/Code-for-Seattle/events/223344967/)?

**Comment by chrismetcalf** [comment]
@karenwittekind At hack night tonight we iterated on a few more ideas we'd like your take on.

![code for seattle](https://cloud.githubusercontent.com/assets/19971/8493435/bad28a2c-210e-11e5-9cbd-5e408883ba0b.png)

Key goals:

- Constrain the logo back into the hexagon so that it'll sit better next to other hexagon logos
- Create a simplified three color logo (#3)
- Bring in the blue of the sound and the cascadia logo
- #4 adds some more texture through two different vector backgrounds from iStockPhoto ([trees](http://www.istockphoto.com/vector/green-poly-abstract-background-67768681?st=45eacab), [water](http://www.istockphoto.com/vector/abstract-water-triangular-pattern-36206342?st=6bc5926))

See what you think and let us know if you're able to do another round in vector based on what I threw together. There's also a request for a version with a Mount Rainier in the background as well, if you're feeling ambitious.

Thank you so much for your help! :beers:

**Comment by karenwittekind** [comment]
Sorry I wasn't able to make it to this week's hack night. I will work on a few more iterations and post them here for feedback. I will almost certainly be at the next one, but in the meantime if anyone has any design needs, feel free to reach out with ideas :)

**Comment by chrismetcalf** [comment]
Wonderful, thanks @karenwittekind!

**Comment by JohnTigue** [comment]
Here's the Cascadian flag on Wikipedia as SVG:
https://en.wikipedia.org/wiki/Doug_Flag#/media/File:Flag_of_Cascadia.svg

If you view the source, the colors are:
- Blue: #121cc0
- White: #ffffff
- Green: #085d05

I am just going to leaving those here for reference if anyone wants to try those out as a variation. They could even still be used with other colors such as the orange as seen here in previous posts.

**Comment by sethvincent** [comment]
Hey @karenwittekind, as you may have noticed we've started using this version of the logo you created: 

![screen shot 2015-09-03 at 5 28 15 pm](https://cloud.githubusercontent.com/assets/164214/9674095/337febd0-5261-11e5-8f8d-c293d0330dbf.png)

It would be awesome if we could get the source files for it and/or meet up to brainstorm alternate versions. 

Our next event is Open Project Night on September 15 if you'd like to attend and hack on the logo that night: http://www.meetup.com/openseattle/events/224613879
