### ISSUE TITLE
Open Seattle orientation event

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#16]
At our last event we talked about making the first Thursday meetup at Socrata focused on orienting new members.

Here's a draft of the description & schedule:

# Open Seattle Orientation

Learn how to get involved in Open Seattle!

Part volunteer orientation, part mixer for meeting others interested in civic technology, our monthly orientation is a chance to learn what Open Seattle members are up to and what kinds of roles you can play.

All skills & skill levels welcome! You may have noticed that we recently renamed Code for Seattle to Open Seattle. We did this in part to better reflect that the work we do involves far more than code. We are also designers, writers, urban planners, community organizers, & more. 

Attend this event to find projects to work on, to meet people that might want to join your project, & to get a better sense of what Open Seattle is all about.

## Schedule:

- 5:30 p.m. – Arrive, get a snack & soda, meet folks
- 6 p.m. – Introductions
- 6:15 p.m. – What is Open Seattle?
- 6:30 p.m. – Overview of Open Seattle projects
- 7 p.m. – Intro to tools we use at Open Seattle (github & slack)
- 7:45 to 8:45 p.m. – Q&A / meet and talk with long-time Open Seattle members & fellow newcomers

**Comment by sethvincent** [comment]
I'm hoping we can break this up into a few facilitators. 

I could take the "What is Open Seattle?" section, and others could take the overview of projects & intro to tools. Volunteers?

I'm open to revisions to the description & schedule, too. But be quick about revision suggestions! I plan to announce the event on meetup this week.

**Comment by sethvincent** [comment]
posted here: http://www.meetup.com/openseattle/events/223857123/

it's not too late to make revisions if I messed anything up.

**Comment by ptressel** [comment]
The trick is going to be...

1) Attracting new folks to actually come to the meeting.
2) Making this still worthwhile for current folks, so they show up to meet the new folks.
3) Getting the projects lined up and ready to pitch, and emphasize the "ready" part so the pitches are time-limited and coherent.  ;-)

Maybe folks with projects can post here?  But...are the folks with projects getting these notifications?  I suspect that request should go out on the Meetup list.

What tools do you have in mind?  (If your answer "Node.js", then I'd be happy to show folks how they can set up a web site quickly using Python and Web2py.  :D :P :D)  Maybe Github Pages and Jekyll?  Socrata API?  OSM?  Other GIS tools?

**Comment by ptressel** [comment]
Ah, I see "tools" is actually in the original post...d'oh.  So just the tools used to organize the Meetup.

**Comment by stedy** [comment]
This is slightly confusing to me, the event as written seems like its catered towards newer members. Does this event mean no more Civic Hacking Night?

**Comment by sethvincent** [comment]
@stedy yep, this is mostly targeted to new folks.

I'm putting together a plan for a revised version of the civic hacking night over here: https://github.com/openseattle/discuss/issues/18

**Comment by sethvincent** [comment]
@ptressel yeah, i'm thinking we'll only have time to cover the tools used by the organization (github, slack, meetup, [anything i'm missing?]). We should include a brief intro to the Socrata API. Other stuff is more project-specific and it would be hard to include everything.

**Comment by ptressel** [comment]
@stedy makes a point that is worrying me too.

So, we have (only) a meeting for new folks.  And then what?  What do they do *next*?  The most successful on-boarding programs I've seen are Mozilla's and HOTOSM's.  They don't just have training, they have (critically) *something for people to do* afterward.  HOTOSM had an issue where new folks showed up at the time of a disaster, and at other times, there weren't active tasks.  At the same time, there was a long standing idea that we should be mapping *in advance* -- it wasn't hard to predict where the need would be.  So...they came up with the Missing Maps project.  Now, new folks have something worthwhile and meaningful to do right out of the gate, no matter when they get involved.

I'd feel like it was false advertising to say to new folks, month after month, sure!  There's plenty to do!  Just work on our own web site!  Oh, and come up with your own project and do your own organizing...

And (back on @stedy's point) another problem with dedicating the *only* regular meetings to new person orientation is that there is now no place for the old folks.  IMO the networking was valuable, even if it was a yackathon rather than a hackathon.

Instead of abandoning getting together to actually Work on Stuff, maybe we should investigate how to make that work, or work better.  This is not a new problem -- it was the wall that CrisisCommons and Random Hacks of Kindness both hit.  But there are lessons from both, and there are likely other CfA groups with ideas.  (I'm willing to spout at length on things to try -- you'll get an earful about such things as the Toyota Manufacturing Process, lean / agile methods, and gamification; and people like W. Edwards Deming, Alistair Cockburn, Patrick Meier, Jane McGonigal, Jim Benson...  Yeah, there will probably be a kanban in there somewhere...but it would be a kanban with fireworks and cheers when you move something to Done.)

As it stands, our on-boarding seems like a Road to Nowhere unless we work on where to go from there.

And for your mulling-it-over pleasure, here are the Talking Heads, with Road to Nowhere:
https://www.youtube.com/watch?v=AWtCittJyr0

**Comment by LukeSwart** [comment]
@ptressel Thanks for the thoughtful comment, you bring up some good points :-)

I look forward to attending the "new folks" meetup, and I'm sure that other Open Seattle members are happy to attend as well. We can start with "What is Open Seattle", do project pitches, and then break into groups as usual. So, if the first bi-weekly meetup of the month is tailored for Welcome New People, then the second should be tailored for Work on Stuff (suggestions are welcome on how to "Work on Stuff" better!). I am happy to help host/organize these events as well.

Instead of meeting every week, I think we can use the extra two weeks for special events and a deep dive on specific projects (ie "Outdoor hack and yack at Seward Park on Saturday", "Community Technology Advisory Board meetups", or "meetup at Jigsaw to work on Hey Duwamish and High Ground Alert"). We should definitely revisit this thread regularly and see how the new schedule is working.

I love the Talking Heads, but I don't want to walk down a Road to Nowhere!

**Comment by ptressel** [comment]
@Luke

Normally I would preface this with "Don't hit me but..." or "Sorry..." but I was just on a discussion thread about how women are always "apologizing" and should Stop That!  I replied, no, we're not apologizing when we say "sorry" -- we're providing a polite signal that we are about to disagree.  And no, I'm not going to "stop it" and be rude instead...but we do need something that is *understood* by hearers to be a polite "about to disagree" signal.  I said, as long as we each know what the signal means, and so long as the signal is polite, and preferably amusing, I'm ok with a substitution.  So...how about "down twinkles"?
https://en.wikipedia.org/wiki/Occupy_movement_hand_signals
Anyhow, you may imagine that I am currently doing "down twinkles" at you.  ;-)

So...

> We can start with "What is Open Seattle", do project pitches, and then break into groups as usual.
You are right that that's "as usual" -- it's basically what we're doing now.  But it's not what's being proposed.

The main disagreement is that making up a meeting structure a priori is like writing the app before figuring out what it's for.  :D  (Note smiley!  Purpose == defusing the sting of "criticism".)  Deciding on how to structure the meetings should be an outcome of a design process that starts with, what is the goal? what are our user stories? what do we know about that works? what features do we need to include to satisfy the goal / user stories?

Is anyone willing to do a brainstorming session? investigate how other (successful) groups deal with the on-boarding, "what next", and "getting stuff done" issues?

**Comment by ptressel** [comment]
> down twinkles
Heh, I see Boston Occupy calls 'em "squid fingers".  Like that better.

**Comment by luke** [comment]
Happy to go with "down twinkles" but I don't think I'm the @Luke you are
after.

- Luke

On Thu, Jul 16, 2015 at 2:55 PM, Pat Tressel <notifications@github.com>
wrote:

> down twinkles
> Heh, I see Boston Occupy calls 'em "squid fingers". Like that better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseattle/discuss/issues/16#issuecomment-121870092>.
>



-- 
--------------------------------------------
Q: Why is this email three sentences or less?
A: http://three.sentenc.es

**Comment by ptressel** [comment]
@Luke -- whoops, sorry!  Ok, fixed.  I thought there was a space after the "Luke" in "LukeSwart", but see there's not.  Also didn't know that "@" was going to poke anyone -- I should go look at the notification options.  You probably will need to "unsubscribe" from this issue...

**Comment by LukeSwart** [comment]
I am open to hearing out new onboarding ideas, and/or getting a brainstorming session going. Whether it's at the next meetup or on this comment thread, let's figure this out.

@ptressel 
Your disagreement is polite and well understood. In the future, I'll hear "squid fingers" loud and clear. I like it! Just say "squid fingers! What about...". BTW you are far too reasonable to sting me with criticism anyway - no worries there :-)

**Comment by sethvincent** [comment]
this is happening now :zap:, so closing this issue.
