### ISSUE TITLE
Event: May 11 at Socrata

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#41]
## Location, date, time:
Socrata
May 11, 2016
6-9 p.m.

## Talks
- Someone from the city (description needed)
- Open data research -- Meg Young & An Yan

## Meetup announcement
http://www.meetup.com/openseattle/events/230722177/

**Comment by ptressel** [comment]
Don't hit me but...is there any chance of revisiting the switch to Wednesdays?  There are likely folks over in the (very large) PuPPy (Puget Sound Programming Python) meetup who'd like to be in Open Seattle, but their monthly meeting is on the same day.  (And also sorry -- I'm going to the PuPPy meetup.)

**Comment by sethvincent** [comment]
We should come up with some alternate dates for June and see if they work for Socrata.

**Comment by LukeSwart** [comment]
@ptressel Thanks for bringing this up! I agree - I think we overlooked this conflict when we made the change. I love PuPPy too!

**Comment by chrismetcalf** [comment]
Given that we are using our main office space now and don't have to worry about conflicts in the shared meeting room downstairs, we can be pretty flexible.

When picking dates, watch out for Mariners and Sounders games, as that can make our neighborhood pretty crazy and jacks the price of parking up.

**Comment by ptressel** [comment]
Luke started an issue for talking about alternate dates here:

https://github.com/openseattle/discuss/issues/43

(Is the "add a link" widget acting oddly for you too?  I pasted in an URL of the other issue.  Since it wasn't obviously going to be converted to a link, I selected the text, and clicked add link.  That prepended something that appears as [] and appended a close parenthesis.  No link, and the entire line is invisible in rendered text.  Seems issue URLs will be rendered as links by default, but using add link shouldn't *break* the link...)

**Comment by chrismetcalf** [comment]
We're gonna have a special Socrata guest for next week too!

**Comment by sethvincent** [comment]
Beryl Fernandes is organizing a privacy & technology event that is on June 8 and it looks pretty interesting: http://www.meetup.com/openseattle/events/230971670/

That event combined with our interest in picking a new recurring date for our talks event (#43), maybe we could try Monday, June 6 for this?

I'm hesitant about a Monday event (because uuuugggg Mondays) but maybe this could be a trial run to see if it would work.
