### ISSUE TITLE
New Open Seattle meetup schedule?

### ISSUE THREAD

**Issue by LukeSwart** [openseattle/discuss#43]
We are currently meeting up on the 2nd and 4th Wednesday every month, which has been working great, except that it conflicts with PuPPy, who meets up on the 2nd Wednesday each month.

Is there a better schedule that works for everyone?

This issue was created in response to [this thread](https://github.com/openseattle/discuss/issues/41#issuecomment-215580868)

---

Here is a quick summary of our approach to decide on a new meetup schedule:
**You input is valuable here - please let us know what you think or if we are missing something**

So it looks like we have these constraints:
 * We should prioritize avoiding [Cugos](http://cugos.org) conflicts (3rd Wed)
 * [Maptime](http://www.meetup.com/maptimeSEA/) (1st Wed), [Seattle-JS](http://www.meetup.com/Seattle-Node-js/) (2nd Thursday), [Puppy](http://www.meetup.com/PSPPython/) (2nd Wed), [Seattle-DAML](http://www.meetup.com/Seattle-DAML/) (4th Tues), [Node-JS](http://www.meetup.com/Seattle-Node-js/) (inconsistently 1st tues-thurs), Pioneer Square Art Walk (1st Thurs), [PyLadies](http://www.meetup.com/Seattle-PyLadies/) (4th Thurs), [New Tech Seattle](http://www.meetup.com/NewTechSeattle/) (2nd Tues) are a secondary priority
 * Tuesdays are out, due to Duck Dodge
 * I think our options are constrained to Mon-Thurs evenings
 * We'd have to check in with Socrata about their schedule, although I believe Metcalf said that the new office allows more flexibility, so I think they are available Mon-Thurs evenings.
 * Any other priorities/constraints? 
 
And here are the possible solutions:
 * We can just keep things as they are now, but Python folks will be conflicted.
 * Or we can change our schedule to **4th Wednesdays for Orientation and 1st Wednesdays for Open Project Nights**. Other good options are listed in [Pat's comment below](https://github.com/openseattle/discuss/issues/43#issuecomment-217939502), which match the constraints above?
 * Any other solutions?

Let me know if there is anything else to consider
**Note that we are updating this list as it changes - but follow the comment thread to see the list in between updates**

**Comment by ptressel** [comment]
FYI, PuPPy is:  http://www.meetup.com/PSPPython/
They have slightly more members in their Meetup group than we do, but they regularly draw a 1-2 hundred to their meetings.

**Comment by ptressel** [comment]
Saaaaay, we could use Actual Data!  E.g. extract the meeting dates of popular tech meetups and weight by (e.g.) # attendees.  Could ask folks which meetups they regularly attend.  Also, could do a poll re. which days of the week are open -- Doodle has a nice 3-state response:  Works!, If we haaaaave to, Nopes.

**Comment by ptressel** [comment]
@chrismetcalf said (over in the original issue):
https://github.com/openseattle/discuss/issues/41#issuecomment-215875986

> Given that we are using our main office space now and don't have to worry about conflicts in the shared meeting room downstairs, we can be pretty flexible.
> 
> When picking dates, watch out for Mariners and Sounders games, as that can make our neighborhood pretty crazy and jacks the price of parking up.

Calendars for the teams (including Seahawks for completeness):

http://seattle.mariners.mlb.com/schedule/index.jsp?c_id=sea
http://www.soundersfc.com/schedule
http://www.seahawks.com/schedule

Mariners schedule is dense, but tends to have alternate weeks of away games...not always the same week of the month.  They seem to have Thursdays off more frequently than other days.  Sounders games are mainly on weekends and on the occasional Wednesday evening.

**Comment by LukeSwart** [comment]
So it looks like we are trying to balance out these priorities:
 * We should prioritize avoiding [Maptime](http://www.meetup.com/maptimeSEA/)/[Cugos](http://cugos.org) conflicts (1st and 3rd Wed)
 * [Seattle-JS](http://www.meetup.com/Seattle-Node-js/) (2nd Thursday), [Puppy](http://www.meetup.com/PSPPython/) (2nd Wed), [Node-JS](http://www.meetup.com/Seattle-Node-js/) (inconsistently 1st tues-thurs), Pioneer Square Art Walk (1st Thurs), [New Tech Seattle](http://www.meetup.com/NewTechSeattle/) (2nd Tues) are a secondary priority
 * Any other priorities/constraints? Also, I think our options are constrained to Tues-Thurs evenings
 * We'd have to check in with Socrata about their schedule, although I believe Metcalf said that the new office allows more flexibility, so I think they are available Tues-Thurs evenings.
 
And here are the possible solutions:
 * We can just keep things as they are now, but Python folks will be conflicted. Otherwise, the 2nd and 4th Wednesdays are simple to remember, and otherwise working out.
 * Or a possible solution, but requires another change: It looks like 1st Tuesday and 4th Wednesdays could work without conflicts, no? But if so, we'd also have to coordinate with the upcoming guest for this June's meetup, or start the new schedule in July.
 * Any other solutions?

Let me know if there is anything more I can add to this

**Comment by ptressel** [comment]
> Also, I think our options are constrained to Tues-Thurs evenings

Are Mondays tapu?  Are you thinking of long weekends that consume Mondays?  Is that more common than long weekends that use Fridays?  July 4 is on a Monday, but that's one day.

> It looks like 1st Tuesday and 4th Wednesdays could work without conflicts, no?

None of the conflicts you listed fall on the 3rd & 4th Tuesday, 3rd & 4th Thursday. 

Node.js is (inconsistently) on 1st Tuesday, so the answer to "no?" is No, no?

Is anyone here going to New Tech Seattle?  That's a networking thing, mainly...

Nearly all Maptime meetups are training, using lessons that are also posted online.  Since these meetups have a limit of maybe 30 people and always fill up, and one can do the lessons remotely, don't worry about conflicts.  Cugos (3rd Wednesday) would be good to avoid.

There are other conflicts not listed.  Just a few that have regular meeting days:
Seattle DAML 4th Tuesdays
PyLadies (PyLaddies welcome), 4th Thursdays

> Otherwise, the 2nd and 4th Wednesdays are simple to remember, and otherwise working out.

Simple to remember is irrelevant, no?  We do not remember our meetups -- Meetup does.  And our calendar tools.  Raise yer hand if you personally remember all the meetups you've signed up for without peeking at your calendar!  Also, that's a big 1000+ person "otherwise", innit?

So, I just sampled a bunch of months, and don't see anything on 3rd Tuesdays (other than one upcoming useR meetup, but they don't have a fixed day of the month).  What about 3rd Tuesday for the main meetup?

I also don't see too much on 1st Mondays or 2nd Tuesdays.  If the long weekend issue is a problem, then not Monday.  I'm betting NTS is not a real priority.  So, what about 2nd Tuesday for the hack night?  Yes, it's not a 2-week spacing.  But I'd bet Seth wants to go to the Node.js 1st Tuesday meetups.

Also, people might like to have informal hack nights (Starbucks...) on other Tuesdays.

Summary counter-proposal:
3rd Tuesday main meetup
2nd Tuesday hack night

Not willing to just roll over and give up attending any more Open Seattle meetups...

**Comment by LukeSwart** [comment]
@ptressel As always, thanks for the input!
>Are Mondays tapu?
Good point. I just updated the constraints to include Mondays. It's just that some people don't like Mondays, but who knows.. Heck, I'm up for Sundays, lol.
>Is anyone here going to New Tech Seattle? That's a networking thing, mainly...
I haven't been to NTS in years, but I think we should keep NTS as a secondary priority. Folks come to Open Seattle to network too, and we are a technology group too, so I figured we should avoid that conflict. But let me know if you disagree.
>Nearly all Maptime meetups are training, using lessons that are also posted online. Since these meetups have a limit of maybe 30 people and always fill up, and one can do the lessons remotely, don't worry about conflicts.
True! But I feel that Maptime has the spirit as Open Seattle, and lots of Open Seattle project involve maps. So I moved it to a "secondary" concern.
>Simple to remember is irrelevant, no? ...
Cool, I removed that as a support for our "keeping things the same" solution.
>3rd Tuesday main meetup, 2nd Tuesday hack night
3rd Tuesday still conflicts with NTS, which I think is still a priority (which is totally up for discussion). How about *3rd Tuesday Orientation (main meetup), 4th Wednesday Open Project Night (hack night)**?

**Comment by ptressel** [comment]
<harumph> If you edit prior comments, it makes the replies to them nonsense.  If you want to *add* a current summary, that's fine.  But please leave the original comments intact.  This is why many comment boards disallow any edits.  If you must edit a comment, point out what was changed. </harumph>

Here are all the Maptime tutorials that have been run locally.  You can do all of these without being at a Maptime session.  Which you're not going to get into anyway unless you're sitting there refreshing the Maptime meetup page.
http://maptimesea.github.io/#our-tutorials

And here is a list of learning resources from various Maptime branches:
http://maptime.io/lessons-resources/

>> 2nd Tuesday hack night
> 4th Wednesday Open Project Night (hack night)

Having the hack night lag rather than precede the main meeting could be good, if it's used as a follow-up.  But we can decide independently on the main meeting and the hack night.  If people add ad hoc hack nights, or want to schedule specific project nights, then that takes pressure off the chosen hack night schedule.

> I haven't been to NTS in years

Again, is anyone going to NTS?

> Heck, I'm up for Sundays, lol.

You can come to Seattle Transit Hikers meetups.  Or Elcano project work parties.

**Comment by LukeSwart** [comment]
>Again, is anyone going to NTS?

I know that NTS is not either of our preferred scenes, but it still draws a lot of people - and 123 registered for the last one. And their group has almost 10K members! Although I'd love to only prioritize our tech meetups like CUGOS, PuPPy, etc, I think we should be welcoming to non-tech people who are interested in collaborating with technical people. And I see NTS as a big funnel for that crowd. So I think we should avoid 2nd Tuesdays. Although it's still up for discussion of course!

**Comment by sethvincent** [comment]
If we change the date of the first event of the month my preference is 1st Tuesday.

A conflict with node.js is better than a conflict with PuPPy. I expect there are more data science python people than data science node.js people, and that makes the switch important to me.

We can move forward with the switch to 1st Tuesday if it works with @chrismetcalf & Socrata, and if it still works for @candacefaber to bring folks from the city.

My opinion is that from now on we should not prioritize planning around conflicts with general technology events. Our emphasis should instead be on doing outreach to people that aren't already attending these kinds of events.

**Comment by ptressel** [comment]
Hah, I was going to say, but wait, no, we can't switch to a Node.js night, cuz Seth!  But then I saw the comment was from Seth.  So, @sethvincent are you sure?  Now often does the Node.js meetup use 1st Tuesdays?  And are you suggesting...

1st Tuesday main meeting
3rd Tuesday hack night

Or t'other way round?

3rd Tuesday main meetup
1st Tuesday hack night

For the latter, at least you wouldn't be forced to ditch a Node.js meetup.

**Comment by sethvincent** [comment]
We can leave Open Project Night on 4th wednesdays for now.

**Comment by chrismetcalf** [comment]
Tuesdays won't work for me, since I've got Duck Dodge 🐦 ⛵  all summer, so I'd like to avoid that if possible. That's a commitment I really don't want to have to make a tradeoff on.

**Comment by ptressel** [comment]
:-D  :-D  :-D  Where's the emo for back to the drawingboard?  :-D  :-D  :-D

Looking back at our various options...  What about 4th Wednesday main meeting and 1st Wednesday project night?  That way, if someone does want to go to Maptime (and manages to get in), they'd be missing only the project night.  Or t'other way round, if it seems "weird" to have the main meeting "later" in the month.

**Comment by LukeSwart** [comment]
Thanks @ptressel ! That all sounds good to me. I linked your comment in the list of solutions at the top, so that we can choose one of your proposed options.

But note that 1st Thursday might be an issue because of the Pioneer Square Art Walk that evening. 

Also, what about **3rd Thursday for Orientation (main meeting), and 4th Wednesday for Open Project Night (hack night)**?

**Comment by ptressel** [comment]
Wasn't going to mention it, but I can't do 3rd Thursday (at all ever) -- local [political party] meeting is that night every month.  So if we use 3rd Thursday, maybe we could use it for the hack night...

What's the issue with the art walk?  Are people from Open Seattle attending that, or do you mean there's increased traffic?

And why, again, are we completely avoiding Mondays?  Is it just because there's a belief that people will forget?  Again, we don't remember on our own any more.  :-D  A quick scan (again) of Mondays shows they are significantly less busy for meetups.  I see almost nothing on 1st and 3rd Mondays.

**Comment by ptressel** [comment]
Over on t'other thread...
[https://github.com/openseattle/discuss/issues/44#issuecomment-218299382](https://github.com/openseattle/discuss/issues/44#issuecomment-218299382)
...Seth says:

> Beryl Fernandes is organizing a privacy & technology event that is on June 8 and it looks pretty interesting: [http://www.meetup.com/openseattle/events/230971670/](http://www.meetup.com/openseattle/events/230971670/)
> 
> That event combined with our interest in picking a new recurring date for our talks event (#43), maybe we could try Monday, June 6 for this?
> 
> I'm hesitant about a Monday event (because uuuugggg Mondays) but maybe this could be a trial run to see if it would work.

That sounds like a good field test for a Monday, and it's early in the month, so we have good choices for the follow-up hack day.  We should do some serious promotion of that date, so folks know it's a change.  Also a chance to get feedback on a proposed schedule.

What date for the hack day would go well with 1st Monday?  How about trying 3rd Monday?  Same fixed 2-week gap as now.  Also on a sparsely used night.

**Comment by ptressel** [comment]
Say...just a suggestion...  If you move the discussion elsewhere, post where you have moved the discussion to.  Thanks?

It appears the selected day -- 2nd Thursday -- is none of the options considered here.  In fact, it conflicts with one of the days that Luke explicitly called out to avoid.  Can we talk about it or is it a done deal?  Is it intended for a one time only thing?  Is choosing a different date each month another option?  Are we giving up on selecting a day?

Apparently the following is where the discussion went off to.  If one was not already subscribed to that channel, one did not get any notice that any discussion was taking place there.  Please note that Slack does not display any channel to which one is not subscribed.  

https://openseattle.slack.com/messages/meetup-planning/

In that channel, there is no reference to any of the three GitHub issues relating to the meeting date selection.  There doesn't appear to have been any attempt, in the Slack discussion, to do any optimization of the date to avoid conflicts with other events.  In fact...there doesn't seem to have been any actual discussion.  Hence, there doesn't appear to have been any use to the work we put in here.  [Insert emo for "humph!"]

(Should we talk about getting rid of one discussion modality or the other?  GitHub is more transparent -- it's public and no joining is needed -- and easier to access.  But this should be another issue, so don't reply here.)

**Comment by timothyclemansinsea** [comment]
I think any and all date planning should be done on Github.

**Comment by LukeSwart** [comment]
If there needs to be a prolonged or real-time discussion, I think Slack can be useful. But if we make any meetup schedule changes on Slack, we should definitely update or create a corresponding Github issue.

It seems like the June orientation date was chosen because we had a guest speaker with schedule limitations, and since we haven't decided on a new meetup schedule, the planning was done ad hoc. We can solve this problem by ensuring our chats and our issue tickets are in sync.

I think our permanent meetup schedule is still TBD, but we should definitely consider the constraints listed above when doing so. The options are pretty well summarized at the top of this page, but just to throw it out there, what about **1st Wednesday for Open Project Night, and 4th Wednesday for Orientation**?

**Comment by chrismetcalf** [comment]
Most Wednesdays (with the exception of June when I'll be on my way back from DC) work for myself and Socrata.

**Comment by candacefaber** [comment]
I'm on board with Wednesdays. I like the 4th / 1st model because it
shortens the time between orientation / talks night and getting started on
projects.

Consistency is important. I don't know if Open Seattle has ambitious to be
a home & meeting place for more civic tech projects. I know of a few
getting started that seem like they would be a good fit, but it would be
helpful to point to consistent days and locations.

**Comment by sethvincent** [comment]
Great! 4th Wednesdays for talks night looks like it will work.

Let's make the first one July 27. And the next Open Project Night will be August 3.

In between now and then I plan to host a few smaller project nights in various places.

I'll make separate issues for those things.

Closing this, but if anything else comes up we can revisit it.
