### ISSUE TITLE
Event: June 9 at Socrata

### ISSUE THREAD

**Issue by chrismetcalf** [openseattle/discuss#44]
## Location, date, time:
Socrata
June 9, 2016
6-9 p.m.

## Talks
- @wubledoo from Socrata talks about Public Safety data

## Meetup announcement
http://www.meetup.com/openseattle/events/231408779/

**Comment by chrismetcalf** [comment]
I know we're still confirming whether or not Wednesday is the right day of the week, but we've got a chance to get @wubledoo to come do a talk about Public Safety data, so I wanted to get it on the calendar. 😃

**Comment by wubledoo** [comment]
That week, I could also do 6/6 (Mon) or 6/9 (Thurs).

**Comment by ptressel** [comment]
Thursday is the day we were using before.  It has fewer conflicts with other meetups than Wednesday but still tends to have a fair number of meetups.  Monday is more open, but may be considered less desirable because people forget about Monday meetups.  :-D  :-D  :-D  On the other hand, people running other meetups have "discovered" Mondays, so it's gradually getting more populated.

**Comment by sethvincent** [comment]
Beryl Fernandes is organizing a privacy & technology event that is on June 8 and it looks pretty interesting: http://www.meetup.com/openseattle/events/230971670/

That event combined with our interest in picking a new recurring date for our talks event (#43), maybe we could try Monday, June 6 for this?

I'm hesitant about a Monday event (because uuuugggg Mondays) but maybe this could be a trial run to see if it would work.

**Comment by wubledoo** [comment]
Hey gang- are we confirmed for June 8?  I'm trying to get my schedule for that week locked down.  Thanks!

**Comment by LukeSwart** [comment]
@wubledoo There was some discussion, and I think we settled on June 9. Are you still available? Here was the discussion: https://openseattle.slack.com/messages/meetup-planning/

I think we forgot to update this thread after our discussion on the Slack channel, sorry for the confusion

**Comment by wubledoo** [comment]
Yes, I can make June 9 work!  Thanks!  (Means I can make a happy hour on the 8th, so bonus for me!)
