### ISSUE TITLE
National Day of Civic Hacking

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#45]
This is coming up on June 4. I have done no work so far to make a Seattle event happen.

Are folks interested in making an event happen to coincide with NDoCH?

My preference would be to organize something small & simple.

**Comment by sethvincent** [comment]
What if we did something like a picnic / hack day in a park?

**Comment by ptressel** [comment]
Last time we talked about outdoor hacking, we didn't find any parks that have power and shade (and tables) -- are there some new options?  (Not a fan of sitting out in the sun for hours.  Already at high risk for melanoma.  Also, can't see the display in the sun.)  We also ran into the cost issue -- park shelter rental was somewhat pricey.  Did we learn anything new during the Parks & Rec hackathon about what's available?  Is there a library with a park-like area nearby?

**Comment by ptressel** [comment]
Could collaborate with other groups, like Invisible College.  Maybe they'd like to schedule Super Happy Dev House on that day.  Or there's the new Capitol Hill Tool Library.

**Comment by will-saunders** [comment]
There's the old PacMed building, now owned by the state. State CIO has a small office there.
I might be able to wrangle use of some space.
http://binged.it/1YdLykA 
Jose Rizal Park next door, with shelters (don't know about power)
Cafe inside (Fare Start)
501 Commons coworking for nonprofits
http://pactower.org/about-pacific-tower/

**Comment by ptressel** [comment]
http://www.seattle.gov/parks/park_detail.asp?id=433
https://www.google.com/maps/place/Dr.+Jose+Rizal+Park/@47.5926743,-122.3203376,16z/data=!4m5!3m4!1s0x54906a96fb9a9bb5:0x7961f5440df0a1dc!8m2!3d47.5931772!4d-122.3187229

The picnic shelter is $170/day, $90/half-day.
http://www.seattle.gov/parks/park_detail.asp?id=433

"Electricity and water are not available at any of the picnic parks" so don't count on this for power.

**Comment by chrismetcalf** [comment]
@candacefaber might be able to help find some space with the city

I'll unfortunately be on the east coast, probably crashing a DC-area event before heading to a family wedding (wedding planners don't properly take into account my open data hackathon schedule...). But I should be able to dig up a Socrata representative if we can get something together.

**Comment by candacefaber** [comment]
This is still coming in on my personal email for some reason. :) Can we
switch to Slack for this?

I can definitely help and maybe even ask Parks if they might sponsor – they
were so thrilled with the hackathon and are interested in supporting in
other ways that make sense for their operations. Since we've had so much
around outdoors stuff lately, we could try that.

I'd also recommend hitting up Microsoft -- maybe this would be a good
occasion to play around with water sensors and other data collection.
(Chicago is doing a beach hack for E.Coli watch – thankfully our spaces are
better managed – but it might be fun to do a bit of a scavenger hunt-style
data collection effort.)

Could be fun to make it into a project rather than a day-long sit-down.

I'm down to have a planning breakout at this Wednesday's Open Seattle –
which, thankfully, I can stay for the whole time!

On Mon, May 9, 2016 at 10:53 AM, Chris Metcalf <notifications@github.com>
wrote:

> @candacefaber <https://github.com/candacefaber> might be able to help
> find some space with the city
>
> I'll unfortunately be on the east coast, probably crashing a DC-area event
> before heading to a family wedding (wedding planners don't properly take
> into account my open data hackathon schedule...). But I should be able to
> dig up a Socrata representative if we can get something together.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/openseattle/discuss/issues/45#issuecomment-217938231>
>



-- 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com <http://www.candacefaber.com>
