### ISSUE TITLE
Projects in the park: July 16

### ISSUE THREAD

**Issue by sethvincent** [openseattle/discuss#49]
## Time, date, location
Noon, Saturday, July 16
Seward Park

## Meetup announcement:
http://www.meetup.com/openseattle/events/232597796/

## Things to bring:
- slushee machine (@LukeSwart)
- snacks
- wifi pucks or phones with tethering (@sethvincent, @LukeSwart)
- extension cords and power strips to reach the outlets (and here is a map of power outlets in Seattle parks: http://www.arcgis.com/home/webmap/viewer.html?webmap=83dd5cac87194f63b0318ab7beb3f510 and it looks like there is a publicly accessible outlet here: http://sewardparkstories.org/#pinoy-picnic-shelter) (of course, if your laptop dies, maybe that means it's time to talk in-person!) (@LukeSwart)

## Suggestions for others to bring:
 - bbq + coals
 - snacks
 - music/speakers
 - wifi pucks or phones with tethering

**Comment by ptressel** [comment]
How many connections can each WiFi hotspot handle?  Last phone hotspot I used supported 5 connections.

IDK about others, but my laptop might get two hours of battery life.  There are folks in the meetup with gear that doesn't run on battery.  I'd say that "talking in person" is going to be happening regardless -- we do tend to yack rather than hack.  The result of not being online will just be that one does not get to do much else at the same time.  Unless there's physical / electronics hacking (without a shop?), seems like leaving Seward Park after a while is a better option and maybe something to plan on.  We could decamp to Tin Umbrella Coffee, where they have both WiFi and power, plus good coffee and pastries.  There are also the Columbia City and New Holly libraries at about the same distance as Tin Umbrella.  But we might get shushed there.  ;-)

**Comment by LukeSwart** [comment]
@ptressel Sounds good!

My phone holds 10 connections, and Seth's phone probably holds at least 10 connections as well. We may get our hands on more hotspots, and other folks can share phones as well. It'll probably be a small casual hangout, but with a slushee machine and arcade machines. Maybe pizza too. We might also find a spot with power as well - I'll do some recon tomorrow evening and update the page with a specific location. If not, I'll find some power packs / generators.

We are doing this a bit ad-hoc, and it won't be as well planned as our usual meet ups. Just plan to have fun!

**Comment by ptressel** [comment]
Here's their picnic info:
"IMPORTANT: Electricity and water is not provided"
www.seattle.gov/parks/Reservations/docs/picnic_brochure.pdf
Yes, there are water fountains and water in restrooms.  But finding a random power outlet (without taking cover plates off things, or taking out lightbulbs <-- note I am !not! suggesting these) is unlikely.  There are public buildings with power and wifi, just not in park picnic areas.

I have multiple external battery packs, but they are only capable of powering phones.  Beware of "universal" laptop / tablet / phone chargers.  They lie.  They may have a few output voltages they support, but nothing like the wide variety that laptops in the wild take.  (Nope, not going to plug your 19V supply into my 18.5V laptop.)  Also, they typically don't have much capacity, so if you want to charge more than one device, they are really only useful for smaller devices like tablets.  Might be better not to waste your money if you don't already have one of these.

I suppose I do need to say this explicitly.  Not everyone in Open Seattle has fancy new devices with 8 hour battery life.  Some people can't afford to replace their older gear.

I'm assuming the slushee machine is hand-powered?  And you don't need power for the arcade machines?  ;-)

It's more fun if one anticipates issues so that things go well.  I'm not being a wet blanket, and I don't intend to be one at your party.  That's why I'm "planning" on going to Tin Umbrella or one of the other fine coffee establishments with power and wifi within a few miles.

**Comment by LukeSwart** [comment]
@ptressel Thanks for the input - I love your insight!

I just want to emphasize that this meetup will be ad-hoc, casual, and just for fun. It might be more of an experiment for future outdoor meetus. I wouldn't count on a whole lot of "getting stuff done" - but who knows :) We can get stuff done **and** have fun, right? 

I just linked a map of power outlets in Seattle Parks. I'll do some recon today and update the meetup page with more info.

I feel you on the equipment situation. My pc only has ~3 hrs of battery life - I have an old bulky Lenovo that I picked up refurbished for $400 on [lenovo's outlet site](http://outlet.lenovo.com/). We will do our best to be inclusive to everyone. If we can't find outlets, we'll bring generators or super duper battery packs.

And if you have further suggestions, or other ways to contribute, just keep in touch!

**Comment by ptressel** [comment]
> We can get stuff done and have fun, right?

Yes, getting stuff done definitely goes with having fun.  It's the opposite that's not so fun, which was sorta the point I was trying to make.  If *other* folks are having fun *by getting stuff done*, it's frustrating to just sit around twiddling one's thumbs.

> I just linked a map of power outlets in Seattle Parks.

Where is it linked?  Could you post that here?  It would be useful to have, seeing as how Seattle Parks completely disowns the provision of power.  Are these licit or illicit power outlets? (c.f. not taking off cover plates or unscrewing light bulbs...)  If they are licit, maybe post about it in Seattle Wiki?

~~Hey.  Maybe those of us who find we can't get work done can go look for Pokemon in Seward Park.~~  No!  I take that back.
